/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVerifyRouteImport } from './routes/_app.verify'
import { Route as AppSourcesRouteImport } from './routes/_app.sources'
import { Route as AppResultsRouteImport } from './routes/_app.results'
import { Route as AppProcessingRouteImport } from './routes/_app.processing'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAboutRouteImport } from './routes/_app.about'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifyRoute = AppVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessingRoute = AppProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AppAboutRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/processing': typeof AppProcessingRoute
  '/results': typeof AppResultsRoute
  '/sources': typeof AppSourcesRoute
  '/verify': typeof AppVerifyRoute
}
export interface FileRoutesByTo {
  '/about': typeof AppAboutRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/processing': typeof AppProcessingRoute
  '/results': typeof AppResultsRoute
  '/sources': typeof AppSourcesRoute
  '/verify': typeof AppVerifyRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/processing': typeof AppProcessingRoute
  '/_app/results': typeof AppResultsRoute
  '/_app/sources': typeof AppSourcesRoute
  '/_app/verify': typeof AppVerifyRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/history'
    | '/processing'
    | '/results'
    | '/sources'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/dashboard'
    | '/history'
    | '/processing'
    | '/results'
    | '/sources'
    | '/verify'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/about'
    | '/_app/dashboard'
    | '/_app/history'
    | '/_app/processing'
    | '/_app/results'
    | '/_app/sources'
    | '/_app/verify'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/verify': {
      id: '/_app/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AppVerifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/results': {
      id: '/_app/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/processing': {
      id: '/_app/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof AppProcessingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppProcessingRoute: typeof AppProcessingRoute
  AppResultsRoute: typeof AppResultsRoute
  AppSourcesRoute: typeof AppSourcesRoute
  AppVerifyRoute: typeof AppVerifyRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppProcessingRoute: AppProcessingRoute,
  AppResultsRoute: AppResultsRoute,
  AppSourcesRoute: AppSourcesRoute,
  AppVerifyRoute: AppVerifyRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
